"""Tests for fisheye_fit.py, the lens-calibration fitter carried in tools/.

The load-bearing behaviour is the model *selection*: the fitter tries several sizes and keeps the one
with the lowest leave-one-out error, so extra terms have to earn their place rather than being added
because a bigger polynomial fits the samples better. These tests use synthetic samples generated from a
known model, so the right answer is known exactly.
"""

import json
import math
import os
import sys

import pytest

sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "tools"))

import fisheye_fit as F

B = F.DEFAULT_B


def _truth(radius_px, coefficients):
    t = math.tan(radius_px / B)
    return sum(c * t ** (2 * k + 1) for k, c in enumerate(coefficients))


VISION_COEFFS = (-214.82028, -246.09173, 130.02845, 1.0, -42.09367) # bot/vision.py's _fisheye_c
RADII = (40.0, 90.0, 150.0, 220.0, 290.0, 360.0, 430.0, 490.0)


def samples_for(coefficients, radii=RADII, noise=0.0):
    out = []
    for i, r in enumerate(radii):
        g = _truth(r, coefficients)
        if noise:
            g += noise * (1 if i % 2 == 0 else -1)
        out.append({"radius_px": r, "ground_mm": g})
    return out


GEOMETRY = {"width": 640, "height": 480, "crop": [0, 0, 0, 0], "fisheye_px_scale": 1.0}


class TestItRecoversAKnownModel:
    def test_exact_samples_return_the_known_coefficients(self):
        model = F.fit_ground_calibration(samples_for(VISION_COEFFS))
        assert model["selected_terms"] == 5
        assert model["selection_reason"] == "lowest leave-one-out RMSE"
        for got, want in zip(model["coefficients"], VISION_COEFFS):
            assert got == pytest.approx(want, abs=1e-6)

    def test_predictions_match_the_known_model(self):
        model = F.fit_ground_calibration(samples_for(VISION_COEFFS))
        calibration = {"model": model}
        for r in (100.0, 300.0, 470.0):
            assert F.predict_ground_mm(calibration, r) == pytest.approx(_truth(r, VISION_COEFFS))

    def test_the_model_is_labelled_so_a_stale_file_can_be_rejected(self):
        model = F.fit_ground_calibration(samples_for(VISION_COEFFS))
        assert model["model_type"] == "odd_power_tan"
        assert model["basis"].startswith("sum(a_k * tan(r / b)")
        assert model["radius_px_range"] == [min(RADII), max(RADII)]
        assert model["sample_count"] == len(RADII)


class TestSelectionRejectsOverfitting:
    def test_a_genuinely_smaller_model_wins(self):
        """Data generated by a single tan(r/b) term: the selector must prefer the 1-term model rather than
        the 5-term one that always fits training samples better."""
        model = F.fit_ground_calibration(samples_for((300.0,), noise=1.0))
        assert model["selected_terms"] == 1

    def test_every_candidate_is_reported_with_both_errors(self):
        model = F.fit_ground_calibration(samples_for(VISION_COEFFS))
        assert [m["terms"] for m in model["fit_metrics"]] == [1, 2, 3, 4, 5]
        for candidate in model["fit_metrics"]:
            assert candidate["training_rmse_mm"] >= 0.0
            assert candidate["leave_one_out_rmse_mm"] is None or candidate["leave_one_out_rmse_mm"] >= 0.0
            assert candidate["exponents"] == [2 * k + 1 for k in range(candidate["terms"])]

    def test_training_error_never_loses_to_validation_on_the_same_data(self):
        """Sanity on the metrics themselves: a bigger basis cannot fit its samples worse."""
        model = F.fit_ground_calibration(samples_for(VISION_COEFFS), max_terms=5)
        train = [m["training_rmse_mm"] for m in model["fit_metrics"]]
        assert train == sorted(train, reverse=True)

    def test_leave_one_out_needs_enough_samples(self):
        model = F.fit_ground_calibration(samples_for((300.0,), radii=RADII[:2]))
        assert all(m["leave_one_out_rmse_mm"] is None for m in model["fit_metrics"])
        assert model["selection_reason"] == "lowest training RMSE"

    def test_max_terms_is_capped_by_the_available_samples(self):
        model = F.fit_ground_calibration(samples_for((300.0,), radii=RADII[:3]), max_terms=5)
        assert [m["terms"] for m in model["fit_metrics"]] == [1, 2]


class TestInputValidation:
    def test_needs_two_samples(self):
        with pytest.raises(ValueError):
            F.fit_ground_calibration([{"radius_px": 1.0, "ground_mm": 1.0}])

    def test_every_sample_needs_both_fields(self):
        with pytest.raises(ValueError):
            F.fit_ground_calibration([{"radius_px": 1.0}, {"radius_px": 2.0, "ground_mm": 3.0}])

    def test_b_must_be_non_zero(self):
        with pytest.raises(ValueError):
            F.fit_ground_calibration(samples_for(VISION_COEFFS), b=0.0)


class TestRmse:
    def test_perfect_prediction_is_zero(self):
        assert F._calculate_rmse([1.0, 2.0], [1.0, 2.0]) == pytest.approx(0.0)

    def test_it_is_the_root_mean_square(self):
        assert F._calculate_rmse([0.0, 0.0], [3.0, 4.0]) == pytest.approx(math.sqrt(12.5))

    def test_empty_input_is_zero_not_an_error(self):
        assert F._calculate_rmse([], []) == 0.0


class TestSaveLoadRoundTrip:
    def test_saves_fits_and_reloads(self, tmp_path):
        path = str(tmp_path / "cal.json")
        saved, written = F.save_calibration(samples_for(VISION_COEFFS), GEOMETRY,
                                            calibration_file=path)
        assert written == path and os.path.isfile(path)
        with open(path, encoding="utf-8") as handle:
            on_disk = json.load(handle)
        assert on_disk["version"] == 1
        assert on_disk["camera_geometry"]["width"] == 640
        assert on_disk["distance_units"] == "mm"

        loaded = F.load_calibration(GEOMETRY, calibration_file=path)
        assert loaded is not None
        assert loaded["model"]["selected_terms"] == 5
        assert F.predict_ground_mm(loaded, 300.0) == pytest.approx(_truth(300.0, VISION_COEFFS))

    def test_a_different_resolution_is_refused(self, tmp_path):
        """Resolution check: a calibration from another frame size must not be used."""
        path = str(tmp_path / "cal.json")
        F.save_calibration(samples_for(VISION_COEFFS), GEOMETRY, calibration_file=path)
        assert F.load_calibration({**GEOMETRY, "width": 1280}, calibration_file=path) is None

    def test_a_different_crop_is_refused(self, tmp_path):
        """...and the extension this lens model needs: the crop moves the optical centre, so a
        calibration taken under a different crop is not the same model."""
        path = str(tmp_path / "cal.json")
        F.save_calibration(samples_for(VISION_COEFFS), GEOMETRY, calibration_file=path)
        assert F.load_calibration({**GEOMETRY, "crop": [10, 0, 0, 0]}, calibration_file=path) is None

    def test_a_different_px_scale_is_refused(self, tmp_path):
        path = str(tmp_path / "cal.json")
        F.save_calibration(samples_for(VISION_COEFFS), GEOMETRY, calibration_file=path)
        assert F.load_calibration({**GEOMETRY, "fisheye_px_scale": 1.5}, calibration_file=path) is None

    def test_a_missing_file_is_none_not_an_error(self, tmp_path):
        assert F.load_calibration(GEOMETRY, calibration_file=str(tmp_path / "nope.json")) is None

    def test_a_corrupt_file_is_none(self, tmp_path):
        path = tmp_path / "cal.json"
        path.write_text("{not json", encoding="utf-8")
        assert F.load_calibration(GEOMETRY, calibration_file=str(path)) is None

    def test_a_file_with_no_model_is_none(self, tmp_path):
        path = tmp_path / "cal.json"
        path.write_text(json.dumps({"version": 1, "camera_geometry": GEOMETRY}), encoding="utf-8")
        assert F.load_calibration(GEOMETRY, calibration_file=str(path)) is None

    def test_a_wrong_model_type_is_none(self, tmp_path):
        path = tmp_path / "cal.json"
        path.write_text(json.dumps({"camera_geometry": GEOMETRY,
                                    "model": {"model_type": "tensorflow", "coefficients": [1]}}),
                        encoding="utf-8")
        assert F.load_calibration(GEOMETRY, calibration_file=str(path)) is None


class TestPredict:
    def _calibration(self, coefficients=VISION_COEFFS):
        return {"model": F.fit_ground_calibration(samples_for(coefficients))}

    def test_clamps_outside_the_fitted_range(self):
        calibration = self._calibration()
        lo, hi = calibration["model"]["radius_px_range"]
        assert F.predict_ground_mm(calibration, 1e6) == pytest.approx(
            F.predict_ground_mm(calibration, hi))
        assert F.predict_ground_mm(calibration, -50.0) == pytest.approx(
            F.predict_ground_mm(calibration, lo))

    def test_missing_inputs_are_none(self):
        calibration = self._calibration()
        assert F.predict_ground_mm(None, 100.0) is None
        assert F.predict_ground_mm(calibration, None) is None
        assert F.predict_ground_mm({"model": {}}, 100.0) is None
        assert F.predict_ground_mm({"model": {"coefficients": [1.0]}}, 100.0) is None

    def test_a_negative_distance_is_rejected(self):
        model = F.fit_ground_calibration(samples_for(VISION_COEFFS))
        model = dict(model)
        # t is negative for positive r here, so this predicts positive...
        model["coefficients"] = [-1.0]
        assert F.predict_ground_mm({"model": model}, 100.0) is not None
        model["coefficients"] = [1.0] # ...and this one negative, which must be refused
        assert F.predict_ground_mm({"model": model}, 100.0) is None


class TestVisionConstants:
    def test_emits_five_coefficients_in_vision_order(self):
        model = F.fit_ground_calibration(samples_for(VISION_COEFFS))
        text = F.vision_constants(model)
        assert text.startswith("_fisheye_b = ")
        assert "_fisheye_c = (" in text
        values = text.split("= (", 1)[1].rstrip(")").split(",")
        assert len(values) == 5
        for got, want in zip(values, VISION_COEFFS):
            assert float(got) == pytest.approx(want, abs=1e-5)

    def test_pads_a_shorter_model_to_five_terms(self):
        model = F.fit_ground_calibration(samples_for((300.0, 0.0, 0.0, 0.0, 0.0)))
        values = F.vision_constants(model).split("= (", 1)[1].rstrip(")").split(",")
        assert len(values) == 5
        assert float(values[4]) == pytest.approx(0.0)


class TestSampleLoading:
    def test_reads_a_json_list(self, tmp_path):
        path = tmp_path / "s.json"
        path.write_text(json.dumps([{"radius_px": 1, "ground_mm": 2}]), encoding="utf-8")
        assert F._load_samples(str(path)) == [{"radius_px": 1, "ground_mm": 2}]

    def test_reads_a_wrapped_dict(self, tmp_path):
        path = tmp_path / "s.json"
        path.write_text(json.dumps({"samples": [{"radius_px": 1, "ground_mm": 2}]}), encoding="utf-8")
        assert F._load_samples(str(path)) == [{"radius_px": 1, "ground_mm": 2}]

    def test_reads_a_csv_with_comments_and_blanks(self, tmp_path):
        path = tmp_path / "s.csv"
        path.write_text("# radius_px, ground_mm\n100, 44.5\n\n200,95.0\n", encoding="utf-8")
        assert F._load_samples(str(path)) == [{"radius_px": 100.0, "ground_mm": 44.5},
                                              {"radius_px": 200.0, "ground_mm": 95.0}]

    def test_rejects_anything_else(self, tmp_path):
        path = tmp_path / "s.json"
        path.write_text(json.dumps({"nope": 1}), encoding="utf-8")
        with pytest.raises(ValueError):
            F._load_samples(str(path))


class TestCli:
    def test_prints_a_fit_without_writing_anything(self, tmp_path, capsys):
        path = tmp_path / "s.json"
        path.write_text(json.dumps(samples_for(VISION_COEFFS)), encoding="utf-8")
        assert F.main([str(path)]) == 0
        out = capsys.readouterr().out
        assert "selected 5 terms" in out
        assert "paste into bot/vision.py" in out
        assert "_fisheye_c" in out

    def test_out_writes_a_loadable_calibration(self, tmp_path, capsys):
        path = tmp_path / "s.json"
        path.write_text(json.dumps(samples_for(VISION_COEFFS)), encoding="utf-8")
        out_path = str(tmp_path / "cal.json")
        assert F.main([str(path), "--out", out_path, "--geometry", json.dumps(GEOMETRY)]) == 0
        capsys.readouterr()
        assert F.load_calibration(GEOMETRY, calibration_file=out_path) is not None
